# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: 🙋  Usage Questions
    url: https://github.com/osl-incubator/xh.git/discussions
    about: |
      Use Xhell's GitHub Discussions to ask "How do I do X with Xhell?".
  - name: 📖  Tutorial
    url: https://github.com/osl-incubator/xh.git
    about: |
      The Xhell tutorial is continually updated and provides an in depth walkthrough
      of how to use the latest release of Xhell.
  - name: 📝  Xhell Code of Conduct
    url: https://github.com/osl-incubator/xh.git/coc/CODE_OF_CONDUCT.md
    about: Expectations for how people will interact with each other on Xhell's GitHub.
